import { createContext, useContext, useState } from 'react';

const T = {
  tr: {
    siteTitle: 'YunusLo1545',
    codeArchive: 'Kod Arşivim',
    archiveDesc: 'içerik · Kişisel referans koleksiyonu',
    snippets: 'Snippets',
    apps: 'Uygulamalar',
    sites: 'Siteler',
    chat: 'Sohbet',
    add: '+ Ekle',
    logout: 'Çıkış',
    login: 'Giriş/Kayıt ol',
    search: 'Ara...',
    allLangs: 'Tüm Diller',
    pinned: 'sabitlenmiş',
    notFound: 'İçerik bulunamadı',
    loading: 'Yükleniyor...',
    noSites: 'Henüz site eklenmemiş.',
    edit: 'Düzenle',
    pin: 'Sabitle',
    unpin: 'Sabiti Kaldır',
    delete: 'Sil',
    back: '← Geri',
    generalChat: 'Genel Sohbet',
    sendMsg: 'Mesaj yaz...',
    send: 'Gönder',
    loginToChat: 'Mesaj göndermek için',
    loginLink: 'giriş yap',
    noMessages: 'Henüz mesaj yok. İlk mesajı gönder.',
    admin: 'Admin',
    newContent: 'Yeni İçerik',
    editContent: 'Düzenle',
    editSite: 'Siteyi Düzenle',
    cancel: '← İptal',
    snippet: 'Snippet',
    app: 'Uygulama',
    site: 'Site',
    adminOnly: '(Sadece Admin)',
    titleLabel: 'Başlık *',
    titlePlaceholder: 'Başlık',
    descLabel: 'Açıklama',
    descPlaceholder: 'Kısa açıklama',
    langLabel: 'Dil',
    codeLabel: 'Kod *',
    codePlaceholder: '// Kodunu buraya yapıştır',
    tagsLabel: 'Etiketler',
    tagsPlaceholder: 'utility, tool, windows (virgülle ayır)',
    imageLabel: 'Resim (Opsiyonel)',
    imageClick: 'Tıkla veya Sürükle',
    removeImage: 'Resmi Kaldır',
    removeFile: 'Dosyayı Kaldır',
    fileSelect: 'Dosya Seç',
    saving: 'Kaydediliyor...',
    save: 'Kaydet',
    addBtn: 'Ekle',
    addSite: 'Site Ekle',
    update: 'Güncelle',
    siteTitle2: 'Başlık *',
    siteTitlePh: 'Site adı',
    urlLabel: 'URL *',
    urlPh: 'https://example.com',
    siteTagsPh: 'tool, referans, docs (virgülle ayır)',
    loginTitle: 'Giriş',
    registerTitle: 'Kayıt',
    usernameLabel: 'Kullanıcı Adı',
    passwordLabel: 'Şifre',
    show: 'göster',
    hide: 'gizle',
    loginBtn: 'Giriş Yap',
    registerBtn: 'Kayıt Ol',
    waiting: 'Bekle...',
    backHome: '← Ana Sayfaya Dön',
    fillAll: 'Tüm alanları doldur.',
  },
  en: {
    siteTitle: 'YunusLo1545',
    codeArchive: 'Code Archive',
    archiveDesc: 'items · Personal reference collection',
    snippets: 'Snippets',
    apps: 'Apps',
    sites: 'Sites',
    chat: 'Chat',
    add: '+ Add',
    logout: 'Logout',
    login: 'Login/Register',
    search: 'Search...',
    allLangs: 'All Languages',
    pinned: 'pinned',
    notFound: 'No content found',
    loading: 'Loading...',
    noSites: 'No sites added yet.',
    edit: 'Edit',
    pin: 'Pin',
    unpin: 'Unpin',
    delete: 'Delete',
    back: '← Back',
    generalChat: 'General Chat',
    sendMsg: 'Type a message...',
    send: 'Send',
    loginToChat: 'To send messages,',
    loginLink: 'log in',
    noMessages: 'No messages yet. Send the first one.',
    admin: 'Admin',
    newContent: 'New Content',
    editContent: 'Edit',
    editSite: 'Edit Site',
    cancel: '← Cancel',
    snippet: 'Snippet',
    app: 'App',
    site: 'Site',
    adminOnly: '(Admin Only)',
    titleLabel: 'Title *',
    titlePlaceholder: 'Title',
    descLabel: 'Description',
    descPlaceholder: 'Short description',
    langLabel: 'Language',
    codeLabel: 'Code *',
    codePlaceholder: '// Paste your code here',
    tagsLabel: 'Tags',
    tagsPlaceholder: 'utility, tool, windows (comma separated)',
    imageLabel: 'Image (Optional)',
    imageClick: 'Click or Drag',
    removeImage: 'Remove Image',
    removeFile: 'Remove File',
    fileSelect: 'Select File',
    saving: 'Saving...',
    save: 'Save',
    addBtn: 'Add',
    addSite: 'Add Site',
    update: 'Update',
    siteTitle2: 'Title *',
    siteTitlePh: 'Site name',
    urlLabel: 'URL *',
    urlPh: 'https://example.com',
    siteTagsPh: 'tool, reference, docs (comma separated)',
    loginTitle: 'Login',
    registerTitle: 'Register',
    usernameLabel: 'Username',
    passwordLabel: 'Password',
    show: 'show',
    hide: 'hide',
    loginBtn: 'Log In',
    registerBtn: 'Register',
    waiting: 'Please wait...',
    backHome: '← Back to Home',
    fillAll: 'Fill in all fields.',
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'tr');
  const toggle = () => setLang(l => {
    const next = l === 'tr' ? 'en' : 'tr';
    localStorage.setItem('lang', next);
    return next;
  });
  return (
    <LangContext.Provider value={{ lang, toggle, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
